trigger: none

pr: none

parameters: # parameters(instead of variables) is used here for template compile time expressions
  - name: RELEASE_TYPE
    displayName: SDK release type
    type: string
    values:
      - beta
      - stable
    default: beta
#  - name: PROJECT_NAME
#    displayName: Project Name
#    type: string
#    default: containerregistry
#  - name: PREVIOUS_RELEASE_TAG
#    displayName: Previous Release Tag
#    type: string
#    default: azure-resourcemanager-containerregistry_2.49.0
#  - name: README_TAG
#    displayName: Readme Tag
#    type: string
#    default: package-2025-03-preview
#  - name: RELEASE_VERSION
#    displayName: Release Version
#    type: string
#    default: 2.50.0-beta.1
#  - name: API_SPECS_ARGS
#    displayName: Api Specs Args
#    type: string
#    default: --modelerfour.lenient-model-deduplication=true --enable-sync-stack=false

variables:
  - group: Release Secrets for GitHub
  - name: MAVEN_CACHE_FOLDER
    value: $(Pipeline.Workspace)/.m2/repository
  - name: MAVEN_OPTS
    value: '-Dmaven.repo.local=$(MAVEN_CACHE_FOLDER)'
  - name: NodeVersion
    value: '20.x'
  - name: JavaVersion
    value: '17'

steps:
  - bash: |
      sudo apt-get install -y --upgrade python3-pip python3-setuptools
      pip3 install --upgrade wheel
      pip3 install --upgrade PyYAML requests
    displayName: Update python

  - task: NodeTool@0
    displayName: 'Install Node.js $(NodeVersion)'
    inputs:
      versionSpec: '$(NodeVersion)'

  - bash: |
      npm install -g autorest
    displayName: 'Install autorest'

  - bash: |
      npm install -g gulp
    displayName: 'Install gulp'

  - bash: |
      git checkout $(PREVIOUS_RELEASE_TAG) -b "release/azure-resourcemanager-$(PROJECT_NAME)/$(RELEASE_VERSION)"
    displayName: 'Create branch for a specific git tag from upstream remote'
    condition: ${{ eq(parameters.RELEASE_TYPE, 'beta') }}

  - bash: |
      export PATH=$JAVA_HOME_11_X64/bin:$PATH
      java -version
      set -x
      gulp codegen --projects $(PROJECT_NAME) --autorest-java @autorest/java@latest --apispecs-args "--tag=$(README_TAG)} $(parameters.API_SPECS_ARGS)"
    displayName: 'Generation from Swagger For Premium'

  - template: ../../eng/common/pipelines/templates/steps/create-pull-request.yml
    parameters:
      PRBranchName: fluent-Premium-generation-$(Build.BuildId)
      CommitMsg: '[Automation] mgmt, local generation for $(parameters.PROJECT_NAME) $(README_TAG)'
      PRTitle: '[Automation] mgmt, local generation for $(parameters.PROJECT_NAME) $(README_TAG)'
      PRLabels: 'Mgmt - Track 2'
      OpenAsDraft: '$(DRAFT_PULL_REQUEST)'
